checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  environment:
    python: '3.6.0'

  dependencies:
    before:
      - 'pipenv install --dev'

  tests:
    override:
      -  pipenv run - pylint-run src/
