checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  environment:
    python: '3.9.9'

  dependencies:
    before:
      - 'pip install pipenv'
      - 'pipenv install --dev'

  tests:
    override:
      -  py-scrutinizer-run
      -  pipenv run -- pylint -v -r y src/
