checks:
  python:
    code_rating: false
    duplicate_code: true

build:
  environment:
    python: '3.6.0'

  dependencies:
    before:
      - 'pip install -r requirements.txt'

  tests:
    override:
      -  pylint-run src/ setup.py version.py
