language: python
os: linux
arch: arm64
dist: focal

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - pipenv lock

install:
  - pipenv sync --dev

before_script:
  - pipenv graph

script:
  - pipenv run pycodestyle --statistics --exclude=test,docs/conf.py
  - pipenv run pylint src/

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - pipenv run -- pip show sqbrite -f
  - pipenv run sqbrite -h
